// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5JjolavqBUjCP3DA4KzgsEWjkxyTr85Y',
    appId: '1:594521281368:web:985c78f47e094bee560b2d',
    messagingSenderId: '594521281368',
    projectId: 'digitotest-ac532',
    authDomain: 'digitotest-ac532.firebaseapp.com',
    storageBucket: 'digitotest-ac532.firebasestorage.app',
    measurementId: 'G-6MGZP0X1FW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM2719e1og7md78pbERYMLZ2DhgQvNtLQ',
    appId: '1:594521281368:android:a3d92afddfa0853d560b2d',
    messagingSenderId: '594521281368',
    projectId: 'digitotest-ac532',
    storageBucket: 'digitotest-ac532.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbfpC2L04_uJoJi7cDD-u7-MbdqTrNx9Y',
    appId: '1:594521281368:ios:8e3b717d3e2c856f560b2d',
    messagingSenderId: '594521281368',
    projectId: 'digitotest-ac532',
    storageBucket: 'digitotest-ac532.firebasestorage.app',
    iosBundleId: 'com.example.digitoApp',
  );
}

//flutter run -d 9DDB193F-00DE-4358-87DA-C212867B60AB
